name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Download dependencies
        run: go mod tidy

      - name: Create .ssh directory for tmp SSH keys 
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o gas-linux-amd64

      - name: Build for macOS
        run: GOOS=darwin GOARCH=amd64 go build -o gas-darwin-amd64

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o gas-windows-amd64.exe

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gas-linux-amd64
            gas-darwin-amd64
            gas-windows-amd64.exe
          body_path: .github/release_template.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}